package nc.message;

public enum PacketType {
    PING,
    CONNECT_SUCCESSFUL,
    CLIENT_AUTHENTICATE,
    CLIENT_JOIN_ROOM,
    CLIENT_SEND_DIRECT_MESSAGE,
    CLIENT_AUTHENTICATION_STATUS,
    CLIENT_REGISTER,
    CLIENT_REGISTER_STATUS,
}
